name: My first Workflow

on: push

jobs:
  
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Checking Node version
        run: node -v
      - name: starting test
        run: npm run test
      - name: list file
        run: ls
        
  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions Bye!"

# By default, jobs run parallely
#To run time in sequence, we use needs.
#RUNNERS - Runners are machine where jobs run..
#Types of Runners
#1.Github-Hosted -eg. windows,MacOS, Ubuntu
#2.Self-Hosted - eg. your own server, your cloud virtual machine.

#USES ACTION (keyword): 
#Action : Reusable piece of code and a type of built in function provided by github..
# Steps- clone a repo


