name: My First CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:

  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # 1. Linting check
      - name: Run lint
        run: npm run lint

      # 2. Run tests
      - name: Run tests
        run: npm test

      # 3. Build project
      - name: Build project
        run: npm run build

  deploy-app:
    needs: ci-pipeline
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy application
        run: echo "Deploying application..."

      - name: List files
        run: ls

# By default, jobs run parallely
#To run time in sequence, we use needs.
#RUNNERS - Runners are machine where jobs run..
#Types of Runners
#1.Github-Hosted -eg. windows,MacOS, Ubuntu
#2.Self-Hosted - eg. your own server, your cloud virtual machine.

#USES ACTION (keyword): 
#Action : Reusable piece of code and a type of built in function provided by github..
# Steps- clone a repo


