name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4 

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm install

      # ✅ 1. Lint
      - name: Run lint
        run: npm run lint

      # ✅ 2. Test
      - name: Run test
        run: npm run test

      # ✅ 3. Build
      - name: Build project
        run: npm run build

  say-bye:
    runs-on: ubuntu-latest  
    needs: say-hello

    steps:
      - name: Print message
        run: echo "Hello, Github Actions Bye!"

  deploy: 
    runs-on: ubuntu-latest
    needs: say-hello

    steps:
      - name: Print Deploy
        run: echo "Deploy step"

# By default, jobs run parallely
#To run time in sequence, we use needs.
#RUNNERS - Runners are machine where jobs run..
#Types of Runners
#1.Github-Hosted -eg. windows,MacOS, Ubuntu
#2.Self-Hosted - eg. your own server, your cloud virtual machine.

#USES ACTION (keyword): 
#Action : Reusable piece of code and a type of built in function provided by github..
# Steps- clone a repo


